const Router = require('express')
const router = new Router()
const userController = require('../controllers/userController')
const authMiddleware = require('../middleware/authMiddleware')
const { handlePayment, handleCaptureOrder} = require('../controllers/paypalController')
// const { testGetOrder } = require('../controllers/paypalController')


router.post('/registration', userController.createAccount)
router.post('/regainquestion', userController.regainAccountQuestion)
router.post('/regainanswer', userController.regainAccountAnswer)
router.post('/login', userController.login)
router.get('/accountStatus', userController.checkUserOnline)
router.get('/auth', authMiddleware, userController.check)
router.get('/auth/accountcharacters', authMiddleware, userController.getAccountCharacters)
router.get('/auth/accountinfo', authMiddleware, userController.getAccountInfo)
router.get('/auth/accountvault', authMiddleware, userController.getAccountVaultInfo)
router.get('/auth/accountwebstore', authMiddleware, userController.getAccountWebstore)
router.post('/auth/accountvault/moveZen', authMiddleware, userController.moveZen)
router.post('/auth/accountvault/moveItemToWebstore', authMiddleware, userController.moveItemToWebstore)
router.post('/auth/accountvault/moveItemToVault', authMiddleware, userController.moveItemToVault)
router.post('/auth/accountvault/moveItemToMarket', authMiddleware, userController.moveItemToMarket)
router.get('/auth/market', authMiddleware, userController.getMarketItems)
router.post('/auth/market/getBackItem', authMiddleware, userController.getBackMarketItem)
router.post('/auth/market/buyMarketItem', authMiddleware, userController.buyMarketItem)
router.post('/auth/accountcharacters/reset', authMiddleware, userController.makeAccountCharacterReset)
router.post('/auth/accountcharacters/grandreset', authMiddleware, userController.makeAccountCharacterGrandReset)
router.get('/voteTOPG', userController.userVoteTOPG)
router.get('/voteExtremetop100', userController.userVoteExtremetop100)
router.get('/voteTop100arena', userController.userVoteTop100arena)
router.get('/voteArenaTop100', userController.userVoteArenaTop100)
router.post('/voteMUOGG', userController.userVoteMUOGG)
// router.get('/voteGamesTop100', userController.userVoteGamesTop100)
router.post('/buyVip', userController.buyVip)
router.post('/cryptocloud-insert-invoice', userController.insertCryptoInvoice)
router.post('/cryptocloud-callback', userController.cryptoCloudPayment)
router.post('/paypal-orders', handlePayment)
router.post('/paypal-orders/capture-order', handleCaptureOrder)
// router.post('/paypal-orders/generate-client-token', generateClientToken)



module.exports = router
